version: "3.9"
services:
  server:
    build:
      context: .
      target: dev
    ports:
      - 3000:3000
    environment:
      MONGODB_URI: mongodb://connido:password@db:27017/connido
      PORT: 3000
      WAIT_HOSTS: db:27017
    volumes:
      - ./src:/app/src
    depends_on:
      - db 
  db:
    image: mongo:4.4-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: connido
    ports:
      - 27017:27017
    volumes:
      # persistent data volume
      - mongodb:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongodb:
