version: "3.9"
services:
  server:
    build:
      context: .
      target: dev
    ports:
      - 3000:3000
  db:
    image: mongo:4.4-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      # persistent data volume
      - mongodb:/data/db

volumes:
  mongodb:
